openapi: 3.0.0
info:
  title: iCare API - Complete Documentation
  version: 1.0.0
  description: |
    API PCare untuk pengelolaan layanan primer BPJS Kesehatan
    
servers:
  - url: http://localhost:3001/api/bpjs/ihs_dev
    description: Proxy Backend Local

paths:
  # ============================== KATALOG I-CARE ==============================
  /{serviceName}/api/rs/validate:
    post:
      $ref: './icare/i-care.yaml#/paths/~1{serviceName}~1api~1rs~1validate/post'
  /{serviceName}/api/pcare/validate:
    post:
      $ref: './icare/i-care.yaml#/paths/~1{serviceName}~1api~1pcare~1validate/post'