openapi: 3.0.0
info:
  title: Medical Record API
  version: 1.0.0
  description: |
    API untuk pengelolaan dan integrasi Rekam Medis Elektronik (RME) BPJS Kesehatan, termasuk insert rekam medis. Dokumentasi ini juga mencakup panduan header autentikasi, signature, kompresi, dan enkripsi data.

    Untuk detail teknis dan contoh kode lengkap, silakan lihat file help.yaml.
tags:
  - name: Rekam Medis
    description: Semua endpoint terkait rekam medis elektronik BPJS Kesehatan

servers:
  - url: http://localhost:3001/api/bpjs/erekammedis_dev
    description: Proxy Backend Local

paths:
  # ============================== INSERT REKAM MEDIS ==============================
  /eclaim/rekammedis/insert:
    $ref: 'rekammedis/insert-rekam-medis.yaml#/paths/~1eclaim~1rekammedis~1insert'

