openapi: 3.0.0
info:
  title: VClaim API - Complete Documentation
  version: 1.0.0
  description: |
    API VClaim untuk pengelolaan klaim BPJS Kesehatan
    
    ## Authentication
    Semua endpoint memerlukan header authentication:
    - `X-cons-id`: Consumer ID dari BPJS Kesehatan
    - `X-timestamp`: Generated unix-based timestamp
    - `X-signature`: Generated signature dengan pola HMAC-256
    - `user_key`: User key untuk akses webservice
    
    ## Signature Generation
    ```
    signature = HMAC-SHA256(consId + "&" + timestamp, secretKey)
    ```
    
    ## Decryption
    Response yang dienkripsi menggunakan AES-256-CBC dengan:
    - Key: 16 karakter pertama dari secretKey
    - IV: 16 karakter terakhir dari secretKey
    
    ## File Structure
    Dokumentasi ini terbagi menjadi beberapa file:
    - `authentication`: Header authentication dan signature
    - `lpk`: Lembar Pengajuan Klaim
    - `monitoring`: Monitoring data klaim dan kunjungan
    - `peserta`: Data peserta BPJS Kesehatan
    - `prb`: Pembuatan Rujuk Balik
    - `rencana-kontrol`: Pembuatan Rencana Kontrol/SPRI
    - `referensi`: Data referensi (diagnosa, poli, faskes, dll)
    - `rujukan`: Pengelolaan rujukan
    - `sep`: Pengelolaan SEP (Surat Eligibilitas Peserta)

servers:
  - url: http://localhost:3001/api/bpjs/vclaim-rest-dev
    description: Proxy Backend Local

tags:
  - name: LPK
    description: Lembar Pengajuan Klaim
  - name: Monitoring
    description: Monitoring data klaim dan kunjungan
  - name: Peserta
    description: Data peserta BPJS Kesehatan
  - name: PRB
    description: Pembuatan Rujuk Balik
  - name: Rencana Kontrol
    description: Pembuatan Rencana Kontrol/SPRI
  - name: Referensi
    description: Data referensi (diagnosa, poli, faskes, dll)
  - name: Rujukan
    description: Pengelolaan rujukan (pencarian, pembuatan, update, delete)
  - name: SEP
    description: Pengelolaan SEP (Surat Eligibilitas Peserta) - pembuatan, update, hapus, pencarian, approval, finger print, dan random question

paths:
  # LPK
  /LPK/insert:
    post:
      $ref: './vclaim/lpk.yaml#/paths/~1LPK~1insert/post'
  /LPK/update:
    put:
      $ref: './vclaim/lpk.yaml#/paths/~1LPK~1update/put'
  /LPK/delete:
    delete:
      $ref: './vclaim/lpk.yaml#/paths/~1LPK~1delete/delete'
  /LPK/TglMasuk/{tglMasuk}/JnsPelayanan/{jnsPelayanan}:
    get:
      $ref: './vclaim/lpk.yaml#/paths/~1LPK~1TglMasuk~1{tglMasuk}~1JnsPelayanan~1{jnsPelayanan}/get'

  # Peserta
  /Peserta/nokartu/{noKartu}/tglSEP/{tglSEP}:
    get:
      $ref: './vclaim/peserta.yaml#/paths/~1Peserta~1nokartu~1{noKartu}~1tglSEP~1{tglSEP}/get'
  /Peserta/nik/{nik}/tglSEP/{tglSEP}:
    get:
      $ref: './vclaim/peserta.yaml#/paths/~1Peserta~1nik~1{nik}~1tglSEP~1{tglSEP}/get'

  # Monitoring (tambahkan semua endpoint monitoring sesuai file modular)
  /Monitoring/Kunjungan/Tanggal/{tanggal}/JnsPelayanan/{jnsPelayanan}:
    get:
      $ref: './vclaim/monitoring.yaml#/paths/~1Monitoring~1Kunjungan~1Tanggal~1{tanggal}~1JnsPelayanan~1{jnsPelayanan}/get'
  /Monitoring/Klaim/Tanggal/{tanggal}/JnsPelayanan/{jnsPelayanan}/Status/{status}:
    get:
      $ref: './vclaim/monitoring.yaml#/paths/~1Monitoring~1Klaim~1Tanggal~1{tanggal}~1JnsPelayanan~1{jnsPelayanan}~1Status~1{status}/get'
  /monitoring/HistoriPelayanan/NoKartu/{noKartu}/tglMulai/{tglMulai}/tglAkhir/{tglAkhir}:
    get:
      $ref: './vclaim/monitoring.yaml#/paths/~1monitoring~1HistoriPelayanan~1NoKartu~1{noKartu}~1tglMulai~1{tglMulai}~1tglAkhir~1{tglAkhir}/get'
  /monitoring/JasaRaharja/JnsPelayanan/{jnsPelayanan}/tglMulai/{tglMulai}/tglAkhir/{tglAkhir}:
    get:
      $ref: './vclaim/monitoring.yaml#/paths/~1monitoring~1JasaRaharja~1JnsPelayanan~1{jnsPelayanan}~1tglMulai~1{tglMulai}~1tglAkhir~1{tglAkhir}/get'

  # PRB (tambahkan semua endpoint PRB sesuai file modular)
  /PRB/insert:
    post:
      $ref: './vclaim/prb.yaml#/paths/~1PRB~1insert/post'
  /PRB/Update:
    put:
      $ref: './vclaim/prb.yaml#/paths/~1PRB~1Update/put'
  /PRB/Delete:
    delete:
      $ref: './vclaim/prb.yaml#/paths/~1PRB~1Delete/delete'
  /prb/{noSrb}/nosep/{noSep}:
    get:
      $ref: './vclaim/prb.yaml#/paths/~1prb~1{noSrb}~1nosep~1{noSep}/get'
  /prb/tglMulai/{tglMulai}/tglAkhir/{tglAkhir}:
    get:
      $ref: './vclaim/prb.yaml#/paths/~1prb~1tglMulai~1{tglMulai}~1tglAkhir~1{tglAkhir}/get'

  # Referensi (tambahkan semua endpoint referensi sesuai file modular)
  /referensi/diagnosa/{parameter}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1diagnosa~1{parameter}/get'
  /referensi/poli/{parameter}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1poli~1{parameter}/get'
  /referensi/faskes/{parameter1}/{parameter2}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1faskes~1{parameter1}~1{parameter2}/get'
  /referensi/dokter/pelayanan/{parameter1}/tglPelayanan/{parameter2}/Spesialis/{parameter3}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1dokter~1pelayanan~1{parameter1}~1tglPelayanan~1{parameter2}~1Spesialis~1{parameter3}/get'
  /referensi/propinsi:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1propinsi/get'
  /referensi/kabupaten/propinsi/{parameter1}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1kabupaten~1propinsi~1{parameter1}/get'
  /referensi/kecamatan/kabupaten/{parameter1}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1kecamatan~1kabupaten~1{parameter1}/get'
  /referensi/diagnosaprb:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1diagnosaprb/get'
  /referensi/obatprb/{parameter1}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1obatprb~1{parameter1}/get'
  /referensi/procedure/{parameter}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1procedure~1{parameter}/get'
  /referensi/kelasrawat:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1kelasrawat/get'
  /referensi/dokter/{parameter}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1dokter~1{parameter}/get'
  /referensi/spesialistik:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1spesialistik/get'
  /referensi/ruangrawat:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1ruangrawat/get'
  /referensi/carakeluar:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1carakeluar/get'
  /referensi/pascapulang:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1pascapulang/get'

  # Rencana Kontrol
  /RencanaKontrol/insert:
    post:
      $ref: './vclaim/rencana-kontrol.yaml#/paths/~1RencanaKontrol~1insert/post'
  /RencanaKontrol/Update:
    put:
      $ref: './vclaim/rencana-kontrol.yaml#/paths/~1RencanaKontrol~1Update/put'
  /RencanaKontrol/Delete:
    delete:
      $ref: './vclaim/rencana-kontrol.yaml#/paths/~1RencanaKontrol~1Delete/delete'
  /RencanaKontrol/InsertSPRI:
    post:
      $ref: './vclaim/rencana-kontrol.yaml#/paths/~1RencanaKontrol~1InsertSPRI/post'
  /RencanaKontrol/UpdateSPRI:
    put:
      $ref: './vclaim/rencana-kontrol.yaml#/paths/~1RencanaKontrol~1UpdateSPRI/put'
  /RencanaKontrol/nosep/{noSEP}:
    get:
      $ref: './vclaim/rencana-kontrol.yaml#/paths/~1RencanaKontrol~1nosep~1{noSEP}/get'
  /RencanaKontrol/noSuratKontrol/{noSuratKontrol}:
    get:
      $ref: './vclaim/rencana-kontrol.yaml#/paths/~1RencanaKontrol~1noSuratKontrol~1{noSuratKontrol}/get'
  /RencanaKontrol/ListRencanaKontrol/Bulan/{bulan}/Tahun/{tahun}/Nokartu/{noKartu}/filter/{filter}:
    get:
      $ref: './vclaim/rencana-kontrol.yaml#/paths/~1RencanaKontrol~1ListRencanaKontrol~1Bulan~1{bulan}~1Tahun~1{tahun}~1Nokartu~1{noKartu}~1filter~1{filter}/get'
  /RencanaKontrol/ListRencanaKontrol/tglAwal/{tglAwal}/tglAkhir/{tglAkhir}/filter/{filter}:
    get:
      $ref: './vclaim/rencana-kontrol.yaml#/paths/~1RencanaKontrol~1ListRencanaKontrol~1tglAwal~1{tglAwal}~1tglAkhir~1{tglAkhir}~1filter~1{filter}/get'
  /RencanaKontrol/ListSpesialistik/JnsKontrol/{jnsKontrol}/nomor/{nomor}/TglRencanaKontrol/{tglRencanaKontrol}:
    get:
      $ref: './vclaim/rencana-kontrol.yaml#/paths/~1RencanaKontrol~1ListSpesialistik~1JnsKontrol~1{jnsKontrol}~1nomor~1{nomor}~1TglRencanaKontrol~1{tglRencanaKontrol}/get'
  /RencanaKontrol/JadwalPraktekDokter/JnsKontrol/{jnsKontrol}/KdPoli/{kdPoli}/TglRencanaKontrol/{tglRencanaKontrol}:
    get:
      $ref: './vclaim/rencana-kontrol.yaml#/paths/~1RencanaKontrol~1JadwalPraktekDokter~1JnsKontrol~1{jnsKontrol}~1KdPoli~1{kdPoli}~1TglRencanaKontrol~1{tglRencanaKontrol}/get'


# Rujukan
  /Rujukan/{noRujukan}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1{noRujukan}/get'
  /Rujukan/RS/{noRujukan}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1RS~1{noRujukan}/get'
  /Rujukan/Peserta/{noKartu}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1Peserta~1{noKartu}/get'
  /Rujukan/RS/Peserta/{noKartu}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1RS~1Peserta~1{noKartu}/get'
  /Rujukan/List/Peserta/{noKartu}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1List~1Peserta~1{noKartu}/get'
  /Rujukan/RS/List/Peserta/{noKartu}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1RS~1List~1Peserta~1{noKartu}/get'
  /Rujukan/insert:
    post:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1insert/post'
  /Rujukan/update:
    put:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1update/put'
  /Rujukan/delete:
    delete:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1delete/delete'
  /Rujukan/Khusus/insert:
    post:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1Khusus~1insert/post'
  /Rujukan/Khusus/delete:
    post:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1Khusus~1delete/post'
  /Rujukan/Khusus/List/Bulan/{bulan}/Tahun/{tahun}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1Khusus~1List~1Bulan~1{bulan}~1Tahun~1{tahun}/get'
  /Rujukan/2.0/insert:
    post:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~12.0~1insert/post'
  /Rujukan/2.0/Update:
    put:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~12.0~1Update/put'
  /Rujukan/ListSpesialistik/PPKRujukan/{kodePPK}/TglRujukan/{tglRujukan}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1ListSpesialistik~1PPKRujukan~1{kodePPK}~1TglRujukan~1{tglRujukan}/get'
  /Rujukan/ListSarana/PPKRujukan/{kodePPK}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1ListSarana~1PPKRujukan~1{kodePPK}/get'
  /Rujukan/Keluar/List/tglMulai/{tglMulai}/tglAkhir/{tglAkhir}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1Keluar~1List~1tglMulai~1{tglMulai}~1tglAkhir~1{tglAkhir}/get'
  /Rujukan/Keluar/{noRujukan}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1Keluar~1{noRujukan}/get'
  /Rujukan/JumlahSEP/{jenisRujukan}/{noRujukan}:
    get:
      $ref: './vclaim/rujukan.yaml#/paths/~1Rujukan~1JumlahSEP~1{jenisRujukan}~1{noRujukan}/get'

  # SEP
  /SEP/1.1/insert:
    post:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~11.1~1insert/post'
  /SEP/1.1/Update:
    put:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~11.1~1Update/put'
  /SEP/Delete:
    delete:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~1Delete/delete'
  /SEP/{noSep}:
    get:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~1{noSep}/get'
  /Rujukan/lastsep/norujukan/{noRujukan}:
    get:
      $ref: './vclaim/sep.yaml#/paths/~1Rujukan~1lastsep~1norujukan~1{noRujukan}/get'
  /SEP/2.0/insert:
    post:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~12.0~1insert/post'
  /SEP/2.0/update:
    put:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~12.0~1update/put'
  /SEP/2.0/delete:
    delete:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~12.0~1delete/delete'
  /sep/JasaRaharja/Suplesi/{noKartu}/tglPelayanan/{tglPelayanan}:
    get:
      $ref: './vclaim/sep.yaml#/paths/~1sep~1JasaRaharja~1Suplesi~1{noKartu}~1tglPelayanan~1{tglPelayanan}/get'
  /sep/KllInduk/List/{noKartu}:
    get:
      $ref: './vclaim/sep.yaml#/paths/~1sep~1KllInduk~1List~1{noKartu}/get'
  /Sep/pengajuanSEP:
    post:
      $ref: './vclaim/sep.yaml#/paths/~1Sep~1pengajuanSEP/post'
  /Sep/aprovalSEP:
    post:
      $ref: './vclaim/sep.yaml#/paths/~1Sep~1aprovalSEP/post'
  /Sep/persetujuanSEP/list/bulan/{bulan}/tahun/{tahun}:
    get:
      $ref: './vclaim/sep.yaml#/paths/~1Sep~1persetujuanSEP~1list~1bulan~1{bulan}~1tahun~1{tahun}/get'
  /Sep/updtglplg:
    put:
      $ref: './vclaim/sep.yaml#/paths/~1Sep~1updtglplg/put'
  /SEP/2.0/updtglplg:
    put:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~12.0~1updtglplg/put'
  /Sep/updtglplg/list/bulan/{bulan}/tahun/{tahun}/{filter}:
    get:
      $ref: './vclaim/sep.yaml#/paths/~1Sep~1updtglplg~1list~1bulan~1{bulan}~1tahun~1{tahun}~1{filter}/get'
  /sep/cbg/{noSep}:
    get:
      $ref: './vclaim/sep.yaml#/paths/~1sep~1cbg~1{noSep}/get'
  /SEP/Internal/{noSep}:
    get:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~1Internal~1{noSep}/get'
  /SEP/Internal/delete:
    delete:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~1Internal~1delete/delete'
  /SEP/FingerPrint/Peserta/{noKartu}/TglPelayanan/{tglPelayanan}:
    get:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~1FingerPrint~1Peserta~1{noKartu}~1TglPelayanan~1{tglPelayanan}/get'
  /SEP/FingerPrint/List/Peserta/TglPelayanan/{tglPelayanan}:
    get:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~1FingerPrint~1List~1Peserta~1TglPelayanan~1{tglPelayanan}/get'
  /SEP/FingerPrint/randomquestion/faskesterdaftar/nokapst/{noKartu}/tglsep/{tglPelayanan}:
    get:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~1FingerPrint~1randomquestion~1faskesterdaftar~1nokapst~1{noKartu}~1tglsep~1{tglPelayanan}/get'
  /SEP/FingerPrint/randomanswer:
    post:
      $ref: './vclaim/sep.yaml#/paths/~1SEP~1FingerPrint~1randomanswer/post'