openapi: 3.0.0
info:
  title: VClaim API - Entry Point
  version: 1.0.0
  description: |
    Entry point dokumentasi VClaim BPJS Kesehatan. Semua endpoint dipecah ke file terpisah berdasarkan domain.

paths:
  # LPK
  /vclaim-rest/LPK/insert:
    post:
      $ref: './vclaim/lpk.yaml#/paths/~1vclaim-rest~1LPK~1insert/post'
  /vclaim-rest/LPK/update:
    put:
      $ref: './vclaim/lpk.yaml#/paths/~1vclaim-rest~1LPK~1update/put'
  /vclaim-rest/LPK/delete:
    delete:
      $ref: './vclaim/lpk.yaml#/paths/~1vclaim-rest~1LPK~1delete/delete'
  /vclaim-rest/LPK/TglMasuk/{tglMasuk}/JnsPelayanan/{jnsPelayanan}:
    get:
      $ref: './vclaim/lpk.yaml#/paths/~1vclaim-rest~1LPK~1TglMasuk~1{tglMasuk}~1JnsPelayanan~1{jnsPelayanan}/get'

  # Peserta
  /vclaim-rest/Peserta/nokartu/{noKartu}/tglSEP/{tglSEP}:
    get:
      $ref: './vclaim/peserta.yaml#/paths/~1vclaim-rest~1Peserta~1nokartu~1{noKartu}~1tglSEP~1{tglSEP}/get'
  /vclaim-rest/Peserta/nik/{nik}/tglSEP/{tglSEP}:
    get:
      $ref: './vclaim/peserta.yaml#/paths/~1vclaim-rest~1Peserta~1nik~1{nik}~1tglSEP~1{tglSEP}/get'

  # Monitoring (tambahkan semua endpoint monitoring sesuai file modular)
  /vclaim-rest/Monitoring/Kunjungan/Tanggal/{tanggal}/JnsPelayanan/{jnsPelayanan}:
    get:
      $ref: './vclaim/monitoring.yaml#/paths/~1vclaim-rest~1Monitoring~1Kunjungan~1Tanggal~1{tanggal}~1JnsPelayanan~1{jnsPelayanan}/get'
  /vclaim-rest/Monitoring/Klaim/Tanggal/{tanggal}/JnsPelayanan/{jnsPelayanan}/Status/{status}:
    get:
      $ref: './vclaim/monitoring.yaml#/paths/~1vclaim-rest~1Monitoring~1Klaim~1Tanggal~1{tanggal}~1JnsPelayanan~1{jnsPelayanan}~1Status~1{status}/get'
  /vclaim-rest/monitoring/HistoriPelayanan/NoKartu/{noKartu}/tglMulai/{tglMulai}/tglAkhir/{tglAkhir}:
    get:
      $ref: './vclaim/monitoring.yaml#/paths/~1vclaim-rest~1monitoring~1HistoriPelayanan~1NoKartu~1{noKartu}~1tglMulai~1{tglMulai}~1tglAkhir~1{tglAkhir}/get'
  /vclaim-rest/monitoring/JasaRaharja/JnsPelayanan/{jnsPelayanan}/tglMulai/{tglMulai}/tglAkhir/{tglAkhir}:
    get:
      $ref: './vclaim/monitoring.yaml#/paths/~1vclaim-rest~1monitoring~1JasaRaharja~1JnsPelayanan~1{jnsPelayanan}~1tglMulai~1{tglMulai}~1tglAkhir~1{tglAkhir}/get'

  # PRB (tambahkan semua endpoint PRB sesuai file modular)
  /vclaim-rest/PRB/insert:
    post:
      $ref: './vclaim/prb.yaml#/paths/~1vclaim-rest~1PRB~1insert/post'
  /vclaim-rest/PRB/Update:
    put:
      $ref: './vclaim/prb.yaml#/paths/~1vclaim-rest~1PRB~1Update/put'
  /vclaim-rest/PRB/Delete:
    delete:
      $ref: './vclaim/prb.yaml#/paths/~1vclaim-rest~1PRB~1Delete/delete'
  /vclaim-rest/prb/{noSrb}/nosep/{noSep}:
    get:
      $ref: './vclaim/prb.yaml#/paths/~1vclaim-rest~1prb~1{noSrb}~1nosep~1{noSep}/get'
  /vclaim-rest/prb/tglMulai/{tglMulai}/tglAkhir/{tglAkhir}:
    get:
      $ref: './vclaim/prb.yaml#/paths/~1vclaim-rest~1prb~1tglMulai~1{tglMulai}~1tglAkhir~1{tglAkhir}/get'

  # Referensi (tambahkan semua endpoint referensi sesuai file modular)
  /referensi/diagnosa/{parameter}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1diagnosa~1{parameter}/get'
  /referensi/poli/{parameter}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1poli~1{parameter}/get'
  /referensi/faskes/{parameter1}/{parameter2}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1faskes~1{parameter1}~1{parameter2}/get'
  /referensi/dokter/pelayanan/{parameter1}/tglPelayanan/{parameter2}/Spesialis/{parameter3}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1dokter~1pelayanan~1{parameter1}~1tglPelayanan~1{parameter2}~1Spesialis~1{parameter3}/get'
  /referensi/propinsi:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1propinsi/get'
  /referensi/kabupaten/propinsi/{parameter1}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1kabupaten~1propinsi~1{parameter1}/get'
  /referensi/kecamatan/kabupaten/{parameter1}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1kecamatan~1kabupaten~1{parameter1}/get'
  /referensi/diagnosaprb:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1diagnosaprb/get'
  /referensi/obatprb/{parameter1}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1obatprb~1{parameter1}/get'
  /referensi/procedure/{parameter}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1procedure~1{parameter}/get'
  /referensi/kelasrawat:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1kelasrawat/get'
  /referensi/dokter/{parameter}:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1dokter~1{parameter}/get'
  /referensi/spesialistik:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1spesialistik/get'
  /referensi/ruangrawat:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1ruangrawat/get'
  /referensi/carakeluar:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1carakeluar/get'
  /referensi/pascapulang:
    get:
      $ref: './vclaim/referensi.yaml#/paths/~1referensi~1pascapulang/get'