openapi: 3.0.0
info:
  title: VClaim API - Complete Documentation
  version: 1.0.0
  description: |
    API VClaim untuk pengelolaan klaim BPJS Kesehatan
    
    ## Authentication
    Semua endpoint memerlukan header authentication:
    - `X-cons-id`: Consumer ID dari BPJS Kesehatan
    - `X-timestamp`: Generated unix-based timestamp
    - `X-signature`: Generated signature dengan pola HMAC-256
    - `user_key`: User key untuk akses webservice
    
    ## Signature Generation
    ```
    signature = HMAC-SHA256(consId + "&" + timestamp, secretKey)
    ```
    
    ## Decryption
    Response yang dienkripsi menggunakan AES-256-CBC dengan:
    - Key: 16 karakter pertama dari secretKey
    - IV: 16 karakter terakhir dari secretKey
    
    ## File Structure
    Dokumentasi ini terbagi menjadi beberapa file:
    - `authentication.yaml`: Header authentication dan signature
    - `lpk.yaml`: Lembar Pengajuan Klaim
    - `monitoring.yaml`: Monitoring data klaim dan kunjungan
    - `peserta.yaml`: Data peserta BPJS Kesehatan
    - `prb.yaml`: Pembuatan Rujuk Balik

servers:
  - url: https://apijkn-dev.bpjs-kesehatan.go.id
    description: Server Development

tags:
  - name: Authentication
    description: Header authentication dan signature untuk VClaim
  - name: LPK
    description: Lembar Pengajuan Klaim
  - name: Monitoring
    description: Monitoring data klaim dan kunjungan
  - name: Peserta
    description: Data peserta BPJS Kesehatan
  - name: PRB
    description: Pembuatan Rujuk Balik

components:
  securitySchemes:
    vclaimAuth:
      type: apiKey
      in: header
      name: X-cons-id
      description: Consumer ID dari BPJS Kesehatan
    vclaimTimestamp:
      type: apiKey
      in: header
      name: X-timestamp
      description: Generated unix-based timestamp
    vclaimSignature:
      type: apiKey
      in: header
      name: X-signature
      description: Generated signature dengan pola HMAC-256
    userKey:
      type: apiKey
      in: header
      name: user_key
      description: User key untuk akses webservice

paths:
  # Authentication endpoints
  /vclaim-rest/auth/example:
    get:
      tags:
        - Authentication
      summary: Authentication Example
      description: Contoh penggunaan header authentication
      operationId: authExample
      security:
        - vclaimAuth: []
        - vclaimTimestamp: []
        - vclaimSignature: []
        - userKey: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Authentication successful"
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  # LPK endpoints
  /vclaim-rest/LPK/example:
    get:
      tags:
        - LPK
      summary: LPK Example
      description: Contoh endpoint LPK (Lembar Pengajuan Klaim)
      operationId: lpkExample
      security:
        - vclaimAuth: []
        - vclaimTimestamp: []
        - vclaimSignature: []
        - userKey: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "LPK endpoint example"
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  # Monitoring endpoints
  /vclaim-rest/Monitoring/example:
    get:
      tags:
        - Monitoring
      summary: Monitoring Example
      description: Contoh endpoint Monitoring
      operationId: monitoringExample
      security:
        - vclaimAuth: []
        - vclaimTimestamp: []
        - vclaimSignature: []
        - userKey: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Monitoring endpoint example"
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  # Peserta endpoints
  /vclaim-rest/Peserta/example:
    get:
      tags:
        - Peserta
      summary: Peserta Example
      description: Contoh endpoint Peserta
      operationId: pesertaExample
      security:
        - vclaimAuth: []
        - vclaimTimestamp: []
        - vclaimSignature: []
        - userKey: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Peserta endpoint example"
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  # PRB endpoints
  /vclaim-rest/PRB/example:
    get:
      tags:
        - PRB
      summary: PRB Example
      description: Contoh endpoint PRB (Program Rujuk Balik)
      operationId: prbExample
      security:
        - vclaimAuth: []
        - vclaimTimestamp: []
        - vclaimSignature: []
        - userKey: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "PRB endpoint example"
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error 