openapi: 3.0.0
info:
  title: PCare Kesadaran API
  version: 1.0.0
  description: Layanan untuk data tingkat kesadaran pasien PCare
servers:
  - url: http://localhost:3001/api/bpjs/pcare-rest-dev
    description: Proxy Backend Local
tags:
  - name: Kesadaran
    description: Data tingkat kesadaran pasien

paths:
  /pcare-rest-dev/kesadaran:
    get:
      tags: [Kesadaran]
      summary: Get Kesadaran
      description: |
        Get Data Kesadaran untuk tingkat kesadaran pasien
        
        ## URL Format
        `{Base URL}/{Service Name}/kesadaran`
        
        ## Authentication
        Semua request memerlukan header authentication yang valid dari BPJS Kesehatan:
        - `x-cons-id`: Consumer ID dari BPJS
        - `x-timestamp`: Unix timestamp saat ini
        - `x-signature`: HMAC-256 signature
        - `x-authorization`: Base64 encoded authorization
        - `user_key`: User key untuk akses webservice
        
        ## Response
        Mengembalikan daftar tingkat kesadaran yang tersedia:
        - `01`: Compos mentis
        - `02`: Somnolence  
        - `03`: Sopor
        - `04`: Coma
        
        ## Example
        ```
        GET https://apijkn-dev.bpjs-kesehatan.go.id/pcare-rest-dev/kesadaran
        ```
        

      parameters:
        - name: x-cons-id
          in: header
          required: true
          schema:
            type: string
          description: Cons ID
        - name: x-timestamp
          in: header
          required: true
          schema:
            type: string
          description: Timestamp
        - name: x-signature
          in: header
          required: true
          schema:
            type: string
          description: Signature
        - name: x-authorization
          in: header
          required: true
          schema:
            type: string
          description: Authorization signature (Base64)
        - name: user_key
          in: header
          required: true
          schema:
            type: string
          description: User Key
      responses:
        '200':
          description: Data kesadaran berhasil ditemukan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KesadaranResponse'
              example:
                response:
                  count: 4
                  list:
                    - kdSadar: "01"
                      nmSadar: "Compos mentis"
                    - kdSadar: "02"
                      nmSadar: "Somnolence"
                    - kdSadar: "03"
                      nmSadar: "Sopor"
                    - kdSadar: "04"
                      nmSadar: "Coma"
                metaData:
                  message: "OK"
                  code: 200
        '403':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Authentication failed"
              example:
                error: "Authentication failed"
        '408':
          description: Request timeout
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: ["null", "object"]
                  metaData:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "REQUEST_TIMEOUT"
                      code:
                        type: integer
                        example: 408
                required: ["metaData"]
              example:
                response: null
                metaData:
                  message: "REQUEST_TIMEOUT"
                  code: 408
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"
              example:
                error: "Internal server error"

components:
  securitySchemes:
    pcareAuth:
      type: apiKey
      in: header
      name: X-cons-id
      description: Consumer ID dari BPJS Kesehatan
    pcareTimestamp:
      type: apiKey
      in: header
      name: X-timestamp
      description: Generated unix-based timestamp
    pcareSignature:
      type: apiKey
      in: header
      name: X-signature
      description: Generated signature dengan pola HMAC-256
    pcareAuthorization:
      type: apiKey
      in: header
      name: X-authorization
      description: Generated signature dengan pola Base64
    userKey:
      type: apiKey
      in: header
      name: user_key
      description: User key untuk akses webservice
  schemas:
    Kesadaran:
      type: object
      properties:
        kdSadar:
          type: string
          description: Kode tingkat kesadaran
          example: "01"
        nmSadar:
          type: string
          description: Nama tingkat kesadaran
          example: "Compos mentis"
    
    KesadaranResponse:
      type: object
      properties:
        response:
          type: object
          properties:
            count:
              type: integer
              description: Jumlah total data kesadaran
            list:
              type: array
              items:
                $ref: '#/components/schemas/Kesadaran'
        metaData:
          type: object
          properties:
            message:
              type: string
              description: Pesan response
            code:
              type: integer
              description: Kode response
