parameters:
  # Parameter untuk kode PPK (digunakan di beberapa endpoint Aplicares)
  KodePPK:
    name: kodeppk
    in: path
    description: Kode PPK (Pemberi Pelayanan Kesehatan)
    required: true
    schema:
      type: string
    example: "PPK001"

  # Parameter untuk kode kelas (digunakan di beberapa endpoint)
  KodeKelas:
    name: kodekelas
    in: query
    description: Kode kelas kamar
    required: true
    schema:
      type: string
    example: "VIP"

  # Parameter untuk kode ruang (digunakan di beberapa endpoint)
  KodeRuang:
    name: koderuang
    in: query
    description: Kode ruangan
    required: true
    schema:
      type: string
    example: "RG01"

  # Parameter untuk paginasi (start)
  StartParameter:
    name: start
    in: path
    description: Nomor awal untuk paginasi
    required: true
    schema:
      type: integer
      minimum: 1
      default: 1
    example: 1

  # Parameter untuk paginasi (limit)
  LimitParameter:
    name: limit
    in: path
    description: Jumlah maksimal item per halaman
    required: true
    schema:
      type: integer
      minimum: 1
      maximum: 100
      default: 10
    example: 10

  # Parameter untuk header Authorization
  AuthorizationHeader:
    name: Authorization
    in: header
    description: Token otorisasi (Bearer token)
    required: true
    schema:
      type: string
    example: "Bearer your_access_token_here"

  # Parameter untuk header Content-Type
  ContentTypeHeader:
    name: Content-Type
    in: header
    description: Tipe konten request
    required: true
    schema:
      type: string
      enum: [application/json]
      default: application/json
    example: "application/json"
